export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const WEATHER_STORE = 'WEATHER_STORE'
export const WEATHER_DELETE = 'WEATHER_DELETE'
export const PROPOSAL_STORE = 'PROPOSAL_STORE'
export const PROPOSAL_DELETE = 'PROPOSAL_DELETE'